### ISSUE TITLE
Level-1 End Page Design

### ISSUE THREAD

**Issue by fuhadkalathingal** [fuhadkalathingal/PhishGuard#46]
[Level-1 End Page](https://fuhadkalathingal.github.io/PhishGuard/level_1/phishing_awareness.html)

This page's design look weird, so your task is to boost up the design and implement a same glitch button on the page to an entry to level 2 page.

**Comment by swarupsahu08** [comment]
Ok thanks @fuhadkalathingal for assigning me with a fresh issue and I hope to contribute a great feature to this amazing project

**Comment by fuhadkalathingal** [comment]
Thankyou so much✨️
If you want any help, feel free to message me👍🏻

**Comment by swarupsahu08** [comment]
@fuhadkalathingal  I think I wasn't able to make changes in the design of the level1 end page but I have added the glitch button to redirect to level 2 game arena.I hope that you would validate the code and merge it.

**Comment by fuhadkalathingal** [comment]
Its ok, first of all I appreciate you for doing the work well👏

**Comment by fuhadkalathingal** [comment]
If you intrested in contributing more on our project, there is another task waiting for you.
If you like our project, just give a star to our project 🌟

**Comment by swarupsahu08** [comment]
Thanks @fuhadkalathingal hope we can connect on linkedin

**Comment by fuhadkalathingal** [comment]
Hhm🤝
